services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    environment:
      - npm_config_cache=/tmp/.npm
    command: make dev