version: '3.8'

services:
  app:
    image: node:20.12.2
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - npm_config_cache=/tmp/.npm
    command: make dev